#!/usr/bin/env bash

# export JAVA_OPTS="-Xms1g -Xmx2g -XX:+UseG1GC -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.timezone=UTC -Dgpt.home=/opt/tomcat/webapps/geoportal -Dgpt.auth.config=${GPT_AUTHENTICATION:-authentication-simple.xml} -Dopensearch.host=opensearch -Dopensearch.port=9200 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
export OPENSEARCH_INITIAL_ADMIN_PASSWORD=JnfcFCUPHQn2RDbs7FLumMx+yuEx9dhz
export gpt_elasticPassword=JnfcFCUPHQn2RDbs7FLumMx+yuEx9dhz
# Other options: authentication-arcgis.xml authentication-ldap.xml authentication-simple.xml
export gpt_authentication=authentication-keycloak.xml
# Used for basic auth, not Keycloak
export geoportal_admin_password=XwJy/dpRsKwyESsQ+kdEbWnI3CtyT12m
export jwtSigningKey=MH/pDwkol2x+GijwiAQycD+g77u4ZfPR
# # Used internally; Nimbus requires 256 bits
# # Generated by Keycloak
# clientSecret=
export keycloakRealm=cwbi
export clientId=datacatalog
export keycloakTokenUrl=https:/dev2.crrel.mil/auth/realms/cwbi/protocol/openid-connect/token
export keycloakAuthUrl=https://host.docker.internal:8443/auth/realms/cwbi/protocol/openid-connect/auth
export redirectUrl=https://dev2.crrel.mil/catalog/keycloak-callback